exports.islami = [
"Menangislah agar dadamu lapang, sholatlah agar hatimu kembali tenang, berdoalah agar pertolongan segera datang.",
"Hidup sederhana tanpa ada hasrat untuk mencari perhatian di hadapan manusia adalah di antara sebab ketenangan hati dan bahagia.",
"Allah akan mendatangkan hari-hari yang membuat kita bahagia, sebab hidup takkan selamanya sulit.",
"Tetaplah bersabar meskipun terasa seluruh duniamu berantakan. Allah tahu lelahmu.",
"Semoga apa pun yang kamu perjuangkan hari ini Allah berikan kelancaran, sehingga berakhir dengan hasil yang memuaskan.",
"Jangan biarkan hatimu mendapat kesenangan karena pujian dari orang lain, kamu akan sedih dengan kecaman mereka suatu hari nanti. - Imam Ghazali7",
"Jika kamu mencintai seseorang, biarkan dia pergi. Jika ia kembali, maka ia milikmu. Namun jika tidak kembali, ketahuilah maka dia bukan milikmu. - Ali bin Abi Thalib8",
"Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan keperluannya. - QS Ath-Thalaq 89",
"Takdir itu milik Allah, namun usaha dan doa adalah milik kita.",
"Jika kamu belajar dari kegagalan, maka kamu tidak akan pernah gagal.",
"Terkadang yang membuatmu gelisah bukanlah masalah yang menguji, tetapi bahasa rindu Allah yang gagal kamu pahami.",
"Dalam hidup, banyak hadiah terbungkus dengan masalah, maka jangan cepat membenci apa yang tidak kamu senangi.",
"Semoga Allah membimbing di setiap langkah, sehingga apapun yang kulakukan menjadi berkah. Dan apapun yang kuusahakan berbuah indah.",
"Sholatlah agar hatimu tenang, istighfarlah agar kecewamu hilang. Dan berdoalah agar bahagiamu segera datang.",
"Masa-masa sulit akan mengajarkanmu bagaimana menjadi kuat dan bagaimana terus berharap kepada Allah.",
"Jangan pernah mendahului apa yang akan terjadi dengan berkata tidak mampu, tidak sanggup, tidak kuat, sebelum ada usaha yang menjadikan dirimu menjadi mampu, sanggup, serta kuat.",
"Takkan pernah ada yang senantiasa bersamamu dalam setiap situasi, kecuali Allah.",
"Titik lelahnya diganti bahagia, fase diamnya diganti senyuman, usahanya diganti keberhasilan, doanya Allah ijabah tepat dengan waktunya.",
"Bercermin itu penting agar kita mengetahui siapa diri kita, apa saja kekurangan kita, sebelum memutuskan untuk menilai orang lain.",
"Kurangi rasa ingin tahumu tentang orang lain, niscaya ghibahmu juga akan berkurang. - Sufyan Ats Tsaury rahimahullah, Siyar A'lam An Nubala 5/62",
"Ceritakan harapan-harapanmu dalam sholat, sebab Allah tak akan mengecewakanmu.",
"Jika memulai karena Allah, maka jangan menyerah karena manusia.",
"Jika ada orang yang menjatuhkanmu bangkitlah karena Allah. Jangan putus asa hanya karena manusia. Jangan menyerah hanya karena urusan dunia, ingat ada Allah. Dia Maha Segalanya. Mohonlah pertolongan pada-Nya.",
"Ketika kamu merasa hidupmu terlalu berat, sudahkah kamu bersyukur atas napasmu hari ini? Sudahkah kamu senyum atas indahnya hari ini?",
"Abaikan rasa sakit hatimu, atau jika tidak, maka kamu akan sulit merasa bahagia.",
"Hidup terasa lebih tenang apabila ikhlas dalam memaafkan.",
"Cara terbaik menghukum orang yang telah melakukan kesalahan terhadap kita ialah dengan berbuat baik kepadanya.",
"Sabar adalah perbendaharaan surga yang tidak diberikan oleh Allah kecuali bagi hamba yang mulia di sisi-Nya. - Imam Abu Hasan Asy'ari29",
"Ketahuilah bahwa dunia pergi semakin jauh, sedangkan akhirat semakin dekat.",
"Jangan khawatir, kamu mungkin tak tahu jodohmu siapa dan jodohmu mungkin tak tahu kamu di mana. Tapi Allah tahu kapan waktu yang tepat untuk mempertemukan kalian berdua.",
"Segala sesuatu dimulai dari yang kecil, kemudian tumbuh membesar, kecuali musibah. Dia besar pada awalnya, kemudian semakin mengecil.",
"Lelahmu akan berubah manis ketika niatnya lillah karena Allah.",
"Semakin kamu menyerahkan semua urusanmu kepada Allah, maka semakin tenang hatimu.",
"Jangan sampai tampilan sudah baik tapi hati masih munafik karena Allah melihat ikhlasnya hati, bukan sucinya penampilan fisik.",
"Terkadang kita terlalu sibuk mencari tanpa kita sadari Allah telah menyiapkan. Kita hanya perlu menjaga dan mempersiapkan.",
"Jangan merasa bahwa rencanamu paling hebat karena sehebat apa pun rencanamu, jika menurut Allah itu tidak baik, Allah tidak akan merestui.",
"Harimu mungkin melelahkan, hatimu merasa terisaukan. Janganlah larut dan tenggelam, Allah selalu menunggumu di sepertiga malam.",
"Saat kamu mulai merasa kehilangan tujuan, ingatlah untuk pulang dan mulailah bersujud pada Tuhan.",
"Jangan bersedih saat keikhlasanmu diragukan, jangan berhenti meski kebaikanmu dilupakan. Saat kita tidak mengharapkan pujian dari orang lain, maka balasan Allah lebih baik dari yang kita harapkan.",
"Jangan berusaha melupakan karena itu akan sangat sulit untuk dilakukan, tapi belajarlah menerima kenyataan agar perlahan hatimu bisa merelakan.",
"Melihatlah ke atas untuk urusan akhiratmu dan melihatlah ke bawah untuk urusan duniamu, maka hidup akan tenteram.",
"Barangsiapa di malam hari merasa kelelahan karena upaya keterampilan kedua tangannya pada siang hari, maka pada malam hari itu ia diampuni oleh Allah. - HR Ahmad43",
"Dan hendaklah mereka memaafkan dan berlapang dada. Apakah kamu tidak ingin bahwa Allah mengampunimu? Dan Allah adalah Maha Pengampun lagi Maha Penyayang. - QS An-Nuur: 2244",
"Jika orang yang kau bantu tidak berterima kasih kepadamu, bisa jadi itu tanda bahwa Allah ingin membesarkan pahalamu dan ingin melihatmu merasakan kelezatan ikhlas.",
"Yakinlah, Allah akan memberikan yang terbaik, bukan yang tercepat.",
"Yakin saja jika melibatkan Allah dalam setiap urusan kita, maka tiada hal yang tidak mungkin.",
"Orang yang hebat adalah orang yang memiliki kemampuan menyembunyikan kemelaratannya, sehingga orang lain menyangka bahwa dia berkecukupan karena dia tidak pernah meminta. - Imam Syafi'i48",
"Barangsiapa mengadu domba untuk kepentinganmu, maka dia akan mengadu domba dirimu, dan barangsiapa menyampaikan fitnah kepadamu, maka ia akan memfitnahmu. - Imam Syafi'i49",
"Dan jadikan sebagian kamu sebagai cobaan bagi sebagian yang lain. Maukah kamu bersabar? - QS Al-Furqan: 2050",
"Balas dendam terbaik adalah menjadikan dirimu lebih baik. - Ali bin Abi Thalib51",
"Kekayaan yang hakiki bukanlah dari banyaknya harta, namun kekayaan yang hakiki adalah hati yang selalu merasa cukup. - HR Bukhari & Muslim52",
"Barangsiapa yang tidak mensyukuri yang sedikit, maka ia tidak akan mampu mensyukuri sesuatu yang banyak.",
"Bila hati kita merasa kurang, itu yang bermasalah adalah hati, bukan rezeki.",
"Kebaikan tidak akan usang, dosa tidak akan dilupakan. Sementara Allah tidak pernah tidur, maka berbuatlah sesukamu, tapi ketahuilah bahwa kelak kau akan dibalas.",
"Kita tahu ini haram, tapi kenapa kita terkadang masih melakukannya? Itu tandanya ilmu kita baru sampai di kepala, belum sampai masuk ke dalam hati.",
"Gelarmu hanyalah selembar kertas, kamu terdidik dengan baik atau tidak lebih terlihat dalam perilakumu.",
"Tiap wadah itu memercikkan isinya. Jika yang keluar dari lisanmu busuk, maka berarti apa yang ada di dalam hatimu pun busuk.",
"Jangan ucapkan segala yang kamu pikirkan. Tapi pikirkanlah segala yang kamu ucapkan.",
"Dtangnya kematian itu tidak menunggu hingga kamu akan menjadi lebih baik, jadilah orang baik dan tunggulah kematian.",
"Sayangilah mereka yang ada di bumi, niscaya mereka yang ada di langit akan menyayangimu. - HR Tirmidzi61",
"Perbanyaklah mengingat Allah karena itu adalah obat. Jangan buat dirimu terlalu banyak mengingat manusia karena itu adalah penyakit. - Umar bin Khattab62",
"Untuk mendapatkan apa yang kamu suka, pertama-tama kamu harus bisa bersabar dengan apa yang kamu benci. - Imam Ghazali63",
"Terkadang orang dengan masa lalu paling kelam akan menciptakan masa depan yang paling cerah. - Umar bin Khattab64",
"Barangsiapa yang tidak menyayangi, maka ia tidak akan disayangi. - HR Bukhari65",
"Dunia itu hanyalah cita-cita yang sirna, ajal yang berkurang, dan jalan menuju akhirat, serta perjalanan menuju kematian. - Umar bin Khattab66",
"Tidak penting siapa kamu di masa lalu, yang terpenting adalah siapa kamu hari ini dan kebaikan apa yang kamu lakukan saat ini.",
"Tidak ada kalimat 'semua akan indah pada waktunya' karena setiap hari pun semuanya terlihat indah jika kita pandai bersyukur.",
"Tidak usah sedih saat rencanamu gagal karena Tuhan menghancurkan rencanamu, agar rencanamu tidak menghancurkanmu.",
"Jika sudah waktunya, hujan akan turun, jika sudah masanya, bunga akan mekar. Jika sudah waktunya, doa-doa pasti akan dikabulkan."
]